---
title: "Papers"
---

This project involved a few different papers, each building off of each other in some way. These papers are listed and described below.

---

"Distinguishing Children's Hospitals from Non-Children's Hospitals in Large Claims Data" with K. Piper, K. Baxter, and M. Raval, *Hospital Pediatrics*, 2020 <br>

<a href=https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6986900/><i class="fas fa-download"> **Download Paper**</i></a><br>

This was the first paper officially related to this project, the goal of which was to establish a credible way to identify "Children's Hospitals" versus "Non-Children's Hospitals" in the data. This is not as obvious as it seems because many hospitals have designated pediatric wings within larger general acute care hospitals. We ultimately propose a four tier system, with Tier A reflecting designated, stand-alone Children's Hospitals, Tier B reflecting general acute care hospitals with a designated pediatric area/wing, Tier C hospitals reflecting general acute care hospitals that offer limited pediatric services, and Tier D hospitals that provide no key pediatric services.

---

"Association of Children's Hospital Status with Value for Common Surgical Conditions" with M. Raval and A. Reiter, *JAMA Network Open*, 2022 <br>

<a href=https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2793553><i class="fas fa-download"> **Download Paper**</i></a><br>


This paper summarizes commercial insurance payments for a set of relatively common pediatric procedures to Children's Hospitals and non-Children's Hospitals. We find higher prices among Children's Hospitals, with no evidence of higher quality. We emphasize, however, that this paper focuses on routine procedures rather than some other highly specialized procedures for which Children's Hospitals have been shown to offer much higher quality.

---

"Price Spillovers for Multi-product Firms: The Case of Specialty Hospitals" with M. Raval, Working Paper <br>

<a href=papers/specialization/jhe-paper-202207.pdf><i class="fas fa-download"> **Download Working Paper**</i></a><br>

<a href=papers/specialization/jhe-appendix-202207.pdf><i class="fas fa-download"> **Download Supplemental Appendix**</i></a><br>


This paper attempts to understand *how* Children's Hospitals are able to negotiate such higher commercial payment rates even for routine procedures for which non-Children's Hospitals appear to provide comparable quality. We consider an "umbrella" or "differentiation" effect, which describes a situation in which, due to perceived quality differences or perhaps due to other non-clinical amenities, Children's Hospitals are essentially isolated from competition from non-Children's Hospitals. 

